### ISSUE TITLE
Form overwrites data if someone else modified it after the form was loaded

### ISSUE THREAD

**Issue by traed** [tunnelbanejakten/wp-tuja#46]

**Comment by mikaelsvensson** [comment]
Similar feature already exists for when crew members submits points. Look at `\tuja\view\PointsShortcode::check_optimistic_lock` for inspiration.

**Comment by mikaelsvensson** [comment]
Also; the optimistic lock mechanism will not work since timestamps are, accidentally, no longer stored since commit `1a6b99129fb2883b3ca3a1b8a44e5150da1c0241`.
